### ISSUE TITLE
Error when Compiling: multiple definition of `_xpath_parser'

### ISSUE THREAD

**Issue by Druidpeter** [ziord/cxml#4]
**Describe the bug**
I create a subdirectory in the repository: "build/", descend to it, and run `cmake ../ -DCMAKE_BUILD_TYPE=Release -DCXML_USE_QUERY_MOD=ON -DCXML_USE_XPATH_MOD=ON -DCXML_BUILD_SHARED_LIB=ON

During the Linking C shared library libcxml.so process:

```
/usr/bin/ld: CMakeFiles/cxml.dir/src/query/cxqapi.c.o:(.data.rel+0x18): multiple definition of `cxml_previous'; CMakeFiles/cxml.dir/src/cxml/cxml.c.o:(.bss+0x138): first defined here
/usr/bin/ld: CMakeFiles/cxml.dir/src/xpath/cxxpeval.c.o:(.bss+0x0): multiple definition of `_xpath_parser'; CMakeFiles/cxml.dir/src/cxml/cxml.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/cxml.dir/src/xpath/cxxplib.c.o:(.bss+0x0): multiple definition of `_xpath_parser'; CMakeFiles/cxml.dir/src/cxml/cxml.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/cxml.dir/src/xpath/cxxpparser.c.o:(.bss+0x0): multiple definition of `_xpath_parser'; CMakeFiles/cxml.dir/src/cxml/cxml.c.o:(.bss+0x0): first defined here
/usr/bin/ld: CMakeFiles/cxml.dir/src/xpath/cxxpresolver.c.o:(.bss+0x0): multiple definition of `_xpath_parser'; CMakeFiles/cxml.dir/src/cxml/cxml.c.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/cxml.dir/build.make:561: libcxml.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/cxml.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**To Reproduce**
I imagine that the compile process occurs smoothly on whatever system your using to build, so I can't really give steps to reproduce other than what else I've given. I'm using Manjaro linux, if that helps. A near fresh install.

**Expected behavior**
I expected the code to compile following the instructions given, at least.

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Browser Firefox
 - Version 22.0.5

**Comment by ziord** [comment]
Hi @Druidpeter! I haven't been chanced to work on this project for a while and so missed your issue notification. Since this issue is now closed, were you able to resolve the problem?

**Comment by Druidpeter** [comment]
Oh! I'm sorry, no, not really. I ended up realizing that the project seemed
not to be actively maintained, and ended up simply closing the issue and
putting my use case on the back-burner. But I can reopen it if you'd like?
I would like to use your library to try and parse the xml output of another
very old application that I don't really have access to the source code of.
Basically it's kind of a hack to get access to the internal state of the
program via the program's old xml save files, if that makes sense? Having a
very small and lightweight library that let's me search for precisely the
data I need would be perfect. I switched over to yxml but... well, that
framework really makes you go through and actually parse the entire
document tag by tag, when really I just need very specific pieces of it,
lol.

**Comment by samsnori** [comment]
Can you reopen this issue. It seems that you should have declared `_cxml_xp_parser _xpath_parser` as an `extern`, then define it in `cxxpparser.c`.  Why do you use a single instance in the first place? To me it would make more sense to allocate an instance for each `cxml_root_node` which would allow for using this library in a multi threaded app too.

**Comment by ziord** [comment]
I’m not sure why but I completely missed @Druidpeter’s last comment. I can reopen the issue. Do you want to work on it @samsnori?

**Comment by samsnori** [comment]
It's a 10 second fix would make more sense if you add a commit with these changes:

> It seems that you should have declared _cxml_xp_parser _xpath_parser as an extern, then define it in cxxpparser.c.
